name: dmce
channels:
  - conda-forge
  - anaconda
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10.9
  - cudatoolkit=11.8  # conda-forge 会自动选择合适版本
  - pytorch::pytorch=2.0.1
  - pytorch::pytorch-cuda=11.8
  - conda-build
  - matplotlib
  - numpy<2
  - scipy
  - h5py
  - scikit-learn
  - tqdm
  - pip
  - pip:
    - pytorch-fid==0.3.0
